# Generated by Django 3.2.12 on 2024-05-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('profiles', models.CharField(blank=True, max_length=100)),
                ('plan_image', models.ImageField(blank=True, upload_to='subscription-plan')),
            ],
        ),
    ]
