# Generated by Django 3.2.12 on 2024-05-09 14:32

import dh_content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('about', models.TextField(default='')),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to=dh_content.models.upload_profile_avatar)),
                ('background', models.ImageField(blank=True, upload_to=dh_content.models.upload_profile_background)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', models.FileField(default='', upload_to='icon-images')),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('picture', models.FileField(default='', upload_to='profile-images')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dh_content.profilelinks')),
            ],
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='', upload_to='profile-images')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dh_content.profilelinks')),
            ],
        ),
        migrations.CreateModel(
            name='UserConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('status', models.BooleanField(default=1)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dh_content.profilelinks')),
                ('social', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dh_content.socialmedia')),
            ],
        ),
    ]
