# Generated by Django 3.2.12 on 2024-05-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelinks',
            name='background_color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
