# Generated by Django 3.2.12 on 2024-08-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_content', '0003_profilelinks_qr_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelinks',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profilelinks',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profilelinks',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='profilelinks',
            name='tittle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profilelinks',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
