# Generated by Django 3.2.12 on 2024-08-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_content', '0004_auto_20240825_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelinks',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
