# Generated by Django 3.2.12 on 2024-08-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_content', '0005_alter_profilelinks_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelinks',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilelinks',
            name='tittle',
            field=models.CharField(max_length=255),
        ),
    ]
