# Generated by Django 3.2.12 on 2024-08-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dh_content', '0006_auto_20240825_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallery',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dh_content.profilelinks'),
        ),
    ]
