# Generated by Django 3.2.12 on 2024-05-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
