# Generated by Django 3.2.12 on 2024-07-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
