# Generated by Django 5.1.3 on 2025-07-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='business',
            new_name='business_card',
        ),
    ]
