# Generated by Django 5.1.3 on 2025-07-06 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_icons/')),
            ],
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.socialmediaplatform'),
        ),
    ]
