# Generated by Django 5.1.3 on 2025-07-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_socialmediaplatform_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome or similar icon class', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
    ]
