# Generated by Django 5.1.3 on 2025-07-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_service_icon_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='google_review_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='cards.businessprofile')),
            ],
        ),
    ]
