# Generated by Django 5.1.3 on 2025-07-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_businessprofile_google_review_link_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='google_review_link',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
