# Generated by Django 5.1.3 on 2025-07-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_businessprofile_google_review_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='google_review_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
