# Generated by Django 5.1.3 on 2025-07-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_businessprofile_google_review_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfileSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('keywords', models.TextField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='cards.businessprofile')),
            ],
        ),
    ]
