# Generated by Django 5.1.3 on 2025-07-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_businessprofileseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_social_links', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='theme_templates/')),
            ],
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='theme_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='cards.themesetting'),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_setting', to='cards.themetemplate'),
        ),
    ]
