# Generated by Django 5.1.3 on 2025-07-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_themesetting_themetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofileseo',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofileseo',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofileseo',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og_images/'),
        ),
        migrations.AddField(
            model_name='businessprofileseo',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofileseo',
            name='twitter_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofileseo',
            name='twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/twitter_images/'),
        ),
        migrations.AddField(
            model_name='businessprofileseo',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofileseo',
            name='keywords',
            field=models.TextField(help_text='Comma-separated keywords'),
        ),
        migrations.CreateModel(
            name='TrackingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_id', models.CharField(blank=True, help_text='e.g. UA-XXXXX-Y or G-XXXXXXX', max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='e.g. 123456789012345', max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='e.g. GTM-XXXXXX', max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='cards.businessprofile')),
            ],
        ),
    ]
