# Generated by Django 5.1.3 on 2025-07-06 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_businessprofileseo_canonical_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='theme_template',
        ),
        migrations.AddField(
            model_name='themesetting',
            name='theme_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_setting', to='cards.themetemplate'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_profile', to='cards.businessprofile'),
        ),
    ]
