# Generated by Django 5.1.3 on 2025-07-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_remove_businessprofile_theme_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesetting',
            name='show_logo',
        ),
        migrations.RemoveField(
            model_name='themesetting',
            name='show_social_links',
        ),
        migrations.AddField(
            model_name='themesetting',
            name='font_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='third_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_setting', to='cards.businessprofile'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='theme_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='cards.themetemplate'),
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_logo', models.BooleanField(default=True)),
                ('show_social_links', models.BooleanField(default=True)),
                ('show_contact_info', models.BooleanField(default=True)),
                ('show_services', models.BooleanField(default=True)),
                ('show_gallery', models.BooleanField(default=True)),
                ('show_map', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_setting', to='cards.businessprofile')),
            ],
        ),
    ]
