# Generated by Django 5.1.3 on 2025-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_remove_themesetting_show_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='google_map',
            field=models.URLField(blank=True, null=True),
        ),
    ]
