# Generated by Django 5.1.3 on 2025-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_businessprofile_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingconfig',
            name='google_property_id',
            field=models.CharField(blank=True, help_text='e.g. YOUR-GA4-PROPERTY-ID', max_length=150),
        ),
        migrations.AlterField(
            model_name='trackingconfig',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='e.g. 123456789012345', max_length=150),
        ),
        migrations.AlterField(
            model_name='trackingconfig',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='e.g. UA-XXXXX-Y or G-XXXXXXX', max_length=150),
        ),
        migrations.AlterField(
            model_name='trackingconfig',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='e.g. GTM-XXXXXX', max_length=150),
        ),
    ]
