# Generated by Django 5.1.3 on 2025-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_trackingconfig_google_property_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='tittle',
            field=models.CharField(default='Office', max_length=20),
        ),
    ]
