# Generated by Django 5.1.3 on 2025-07-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_phonenumber_tittle'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
