# Generated by Django 5.1.3 on 2025-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_themesetting_profile_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesetting',
            name='theme_template',
        ),
        migrations.AddField(
            model_name='themesetting',
            name='theme_template',
            field=models.ManyToManyField(blank=True, null=True, related_name='template', to='cards.themetemplate'),
        ),
    ]
