# Generated by Django 5.1.3 on 2025-07-23 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_remove_themesetting_theme_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesetting',
            name='theme_template',
        ),
        migrations.AddField(
            model_name='themesetting',
            name='theme_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='cards.themetemplate'),
        ),
    ]
